add_executable(Task1 Task1.cpp)
add_executable(Task2 Task2.cpp)

target_include_directories(Task1 PRIVATE ../LibraryCPP)
target_include_directories(Task2 PRIVATE ../LibraryCPP)
target_link_libraries(Task1 PRIVATE LibraryCPP)
target_link_libraries(Task2 PRIVATE LibraryCPP)

add_test(NAME Task1_Test1 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_1_Test1)
set_tests_properties(Task1_Test1 PROPERTIES PASS_REGULAR_EXPRESSION "Количество элементов больше суммы: 3")
add_test(NAME Task1_Test2 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_1_Test2)
set_tests_properties(Task1_Test2 PROPERTIES PASS_REGULAR_EXPRESSION "Количество элементов больше суммы: 0")
add_test(NAME Task1_Test3 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_1_Test3)
set_tests_properties(Task1_Test3 PROPERTIES PASS_REGULAR_EXPRESSION "Количество элементов больше суммы: 0")
add_test(NAME Task1_Test4 COMMAND Task1 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_1_Test4)
set_tests_properties(Task1_Test4 PROPERTIES PASS_REGULAR_EXPRESSION "Количество элементов больше суммы: 2")

add_test(NAME Task2_Test1 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_2_Test1)
set_tests_properties(Task2_Test1 PROPERTIES PASS_REGULAR_EXPRESSION "Элементы встречающиеся один раз: 0 2 1000")
add_test(NAME Task2_Test2 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_2_Test2)
set_tests_properties(Task2_Test2 PROPERTIES PASS_REGULAR_EXPRESSION "Элементы встречающиеся один раз: 5 4 3 2 1")
add_test(NAME Task2_Test3 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_2_Test3)
set_tests_properties(Task2_Test3 PROPERTIES PASS_REGULAR_EXPRESSION "Элементы встречающиеся один раз: нет")
add_test(NAME Task2_Test4 COMMAND Task2 ${CMAKE_CURRENT_SOURCE_DIR}/Tests/Task_2_Test4)
set_tests_properties(Task2_Test4 PROPERTIES PASS_REGULAR_EXPRESSION "Элементы встречающиеся один раз: 1000 5")
