add_executable(Lab3CPPTask task.cpp)
target_include_directories(Lab3CPPTask PUBLIC ../LibraryCPPTemplate)

add_test(NAME EXAMPLE COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/example_test.txt")
set_property(TEST EXAMPLE PROPERTY PASS_REGULAR_EXPRESSION "4")


add_test(NAME TEST_1 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test1.txt")
set_property(TEST TEST_1 PROPERTY PASS_REGULAR_EXPRESSION "6")

add_test(NAME TEST_2 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test2.txt")
set_property(TEST TEST_2 PROPERTY PASS_REGULAR_EXPRESSION "4")

add_test(NAME TEST_3 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test3.txt")
set_property(TEST TEST_3 PROPERTY PASS_REGULAR_EXPRESSION "2")

add_test(NAME TEST_4 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test4.txt")
set_property(TEST TEST_4 PROPERTY PASS_REGULAR_EXPRESSION "0")

add_test(NAME TEST_5 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test5.txt")
set_property(TEST TEST_5 PROPERTY PASS_REGULAR_EXPRESSION "9")

add_test(NAME TEST_6 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test6.txt")
set_property(TEST TEST_6 PROPERTY PASS_REGULAR_EXPRESSION "9")

add_test(NAME TEST_7 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test7.txt")
set_property(TEST TEST_7 PROPERTY PASS_REGULAR_EXPRESSION "7")

add_test(NAME TEST_8 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test8.txt")
set_property(TEST TEST_8 PROPERTY PASS_REGULAR_EXPRESSION "4")

add_test(NAME TEST_9 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test9.txt")
set_property(TEST TEST_9 PROPERTY PASS_REGULAR_EXPRESSION "0")

add_test(NAME TEST_10 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test10.txt")
set_property(TEST TEST_10 PROPERTY PASS_REGULAR_EXPRESSION "1")

add_test(NAME TEST_11 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test11.txt")
set_property(TEST TEST_11 PROPERTY PASS_REGULAR_EXPRESSION "")

add_test(NAME TEST_12 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test12.txt")
set_property(TEST TEST_12 PROPERTY PASS_REGULAR_EXPRESSION "")

add_test(NAME TEST_13 COMMAND Lab3CPPTask "${CMAKE_CURRENT_SOURCE_DIR}/tests/test13.txt")
set_property(TEST TEST_13 PROPERTY PASS_REGULAR_EXPRESSION "")
